---
  - name: EOEPCA local development environment
    hosts: all
    become: yes
    roles:
      - common
      - fastcgi
      - devtoolset-7-toolchain
      - robertdebock.git
      - gantsign.visual-studio-code
      - bbaassssiiee.ansible_role_cmake
      - gantsign.minikube
