---
  - name: EOEPCA local development environment
    hosts: all
    become: yes
    roles:
      - common
      - fastcgi
      - devtoolset-7-toolchain
      - geerlingguy.git
      - geerlingguy.java
      - gantsign.visual-studio-code
      - bbaassssiiee.ansible_role_cmake
