---
  - name: EOEPCA local development environment for C++
    hosts: all
    become: yes
    roles:
      - common
      - fastcgi
      - devtoolset-7-toolchain
      - minikube
      - robertdebock.git
      - gantsign.visual-studio-code
      - bbaassssiiee.ansible_role_cmake
      - andrewrothstein.jq

    vars:  
      minikube_version: 1.6.2
      docker_version: 19.03.5
      kubectl_version: 1.17.0

      git_additional_packages:
        - "{% if ansible_os_family == 'FreeBSD' %}gitflow{% elif ansible_os_family == 'OpenBSD' %}git-cvs{% elif ansible_os_family == 'RedHat' %}git-cvs{% else %}git-flow{% endif %}"