# from galaxy
- src: robertdebock.git
- src: gantsign.visual-studio-code
- src: bbaassssiiee.ansible_role_cmake
#- src: geerlingguy.docker
- src: andrewrothstein.jq
#- src: geerlingguy.swap
#- src: geerlingguy.kubernetes
#- src: gantsign.minikube